export function handleError(message) {
	console.log(message);
	process.exit(1);
}
